language: php

php:
  - 5.3
  - 5.4
  - 5.5
  - 5.6
  - 5.7
  - 7.0
  - 7.1
  - 7.2
  - hhvm

matrix:
  env:
    - MAGENTO_VERSION=magento-ce-1.9.3.7
  script:
    - curl -sSL https://raw.githubusercontent.com/AOEpeople/MageTestStand/master/setup.sh | bash

notifications:
  email:
    recipients:
      - github-sr@hotmail.com
  on_success: always
  on_failure: always